package cn.edu.njust.dev.ses.main.model;

import java.util.Date;

public class Application {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.aid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.uid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.app_time
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Date appTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.app_status
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private String appStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.eid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Integer eid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Application(Integer aid, Integer uid, Date appTime, String appStatus, Integer eid) {
        this.aid = aid;
        this.uid = uid;
        this.appTime = appTime;
        this.appStatus = appStatus;
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Application() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.aid
     *
     * @return the value of application.aid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.aid
     *
     * @param aid the value for application.aid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.uid
     *
     * @return the value of application.uid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.uid
     *
     * @param uid the value for application.uid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.app_time
     *
     * @return the value of application.app_time
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Date getAppTime() {
        return appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.app_time
     *
     * @param appTime the value for application.app_time
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setAppTime(Date appTime) {
        this.appTime = appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.app_status
     *
     * @return the value of application.app_status
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.app_status
     *
     * @param appStatus the value for application.app_status
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setAppStatus(String appStatus) {
        this.appStatus = appStatus == null ? null : appStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.eid
     *
     * @return the value of application.eid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.eid
     *
     * @param eid the value for application.eid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }
}