package cn.edu.njust.dev.ses.main.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class DetailedApplicationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public DetailedApplicationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andEidIsNull() {
            addCriterion("eid is null");
            return (Criteria) this;
        }

        public Criteria andEidIsNotNull() {
            addCriterion("eid is not null");
            return (Criteria) this;
        }

        public Criteria andEidEqualTo(Integer value) {
            addCriterion("eid =", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotEqualTo(Integer value) {
            addCriterion("eid <>", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThan(Integer value) {
            addCriterion("eid >", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidGreaterThanOrEqualTo(Integer value) {
            addCriterion("eid >=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThan(Integer value) {
            addCriterion("eid <", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidLessThanOrEqualTo(Integer value) {
            addCriterion("eid <=", value, "eid");
            return (Criteria) this;
        }

        public Criteria andEidIn(List<Integer> values) {
            addCriterion("eid in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotIn(List<Integer> values) {
            addCriterion("eid not in", values, "eid");
            return (Criteria) this;
        }

        public Criteria andEidBetween(Integer value1, Integer value2) {
            addCriterion("eid between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andEidNotBetween(Integer value1, Integer value2) {
            addCriterion("eid not between", value1, value2, "eid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andAidIsNull() {
            addCriterion("aid is null");
            return (Criteria) this;
        }

        public Criteria andAidIsNotNull() {
            addCriterion("aid is not null");
            return (Criteria) this;
        }

        public Criteria andAidEqualTo(Integer value) {
            addCriterion("aid =", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotEqualTo(Integer value) {
            addCriterion("aid <>", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThan(Integer value) {
            addCriterion("aid >", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThanOrEqualTo(Integer value) {
            addCriterion("aid >=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThan(Integer value) {
            addCriterion("aid <", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThanOrEqualTo(Integer value) {
            addCriterion("aid <=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidIn(List<Integer> values) {
            addCriterion("aid in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotIn(List<Integer> values) {
            addCriterion("aid not in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidBetween(Integer value1, Integer value2) {
            addCriterion("aid between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotBetween(Integer value1, Integer value2) {
            addCriterion("aid not between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andAppTimeIsNull() {
            addCriterion("app_time is null");
            return (Criteria) this;
        }

        public Criteria andAppTimeIsNotNull() {
            addCriterion("app_time is not null");
            return (Criteria) this;
        }

        public Criteria andAppTimeEqualTo(Date value) {
            addCriterionForJDBCDate("app_time =", value, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("app_time <>", value, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("app_time >", value, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("app_time >=", value, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeLessThan(Date value) {
            addCriterionForJDBCDate("app_time <", value, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("app_time <=", value, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeIn(List<Date> values) {
            addCriterionForJDBCDate("app_time in", values, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("app_time not in", values, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("app_time between", value1, value2, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("app_time not between", value1, value2, "appTime");
            return (Criteria) this;
        }

        public Criteria andAppStatusIsNull() {
            addCriterion("app_status is null");
            return (Criteria) this;
        }

        public Criteria andAppStatusIsNotNull() {
            addCriterion("app_status is not null");
            return (Criteria) this;
        }

        public Criteria andAppStatusEqualTo(String value) {
            addCriterion("app_status =", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusNotEqualTo(String value) {
            addCriterion("app_status <>", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusGreaterThan(String value) {
            addCriterion("app_status >", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusGreaterThanOrEqualTo(String value) {
            addCriterion("app_status >=", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusLessThan(String value) {
            addCriterion("app_status <", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusLessThanOrEqualTo(String value) {
            addCriterion("app_status <=", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusLike(String value) {
            addCriterion("app_status like", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusNotLike(String value) {
            addCriterion("app_status not like", value, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusIn(List<String> values) {
            addCriterion("app_status in", values, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusNotIn(List<String> values) {
            addCriterion("app_status not in", values, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusBetween(String value1, String value2) {
            addCriterion("app_status between", value1, value2, "appStatus");
            return (Criteria) this;
        }

        public Criteria andAppStatusNotBetween(String value1, String value2) {
            addCriterion("app_status not between", value1, value2, "appStatus");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(String value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(String value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(String value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(String value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(String value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(String value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLike(String value) {
            addCriterion("student_id like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotLike(String value) {
            addCriterion("student_id not like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<String> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<String> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(String value1, String value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(String value1, String value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("gender like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("gender not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andIdNoIsNull() {
            addCriterion("id_no is null");
            return (Criteria) this;
        }

        public Criteria andIdNoIsNotNull() {
            addCriterion("id_no is not null");
            return (Criteria) this;
        }

        public Criteria andIdNoEqualTo(String value) {
            addCriterion("id_no =", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoNotEqualTo(String value) {
            addCriterion("id_no <>", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoGreaterThan(String value) {
            addCriterion("id_no >", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoGreaterThanOrEqualTo(String value) {
            addCriterion("id_no >=", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoLessThan(String value) {
            addCriterion("id_no <", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoLessThanOrEqualTo(String value) {
            addCriterion("id_no <=", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoLike(String value) {
            addCriterion("id_no like", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoNotLike(String value) {
            addCriterion("id_no not like", value, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoIn(List<String> values) {
            addCriterion("id_no in", values, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoNotIn(List<String> values) {
            addCriterion("id_no not in", values, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoBetween(String value1, String value2) {
            addCriterion("id_no between", value1, value2, "idNo");
            return (Criteria) this;
        }

        public Criteria andIdNoNotBetween(String value1, String value2) {
            addCriterion("id_no not between", value1, value2, "idNo");
            return (Criteria) this;
        }

        public Criteria andEthnicGroupIsNull() {
            addCriterion("ethnic_group is null");
            return (Criteria) this;
        }

        public Criteria andEthnicGroupIsNotNull() {
            addCriterion("ethnic_group is not null");
            return (Criteria) this;
        }

        public Criteria andEthnicGroupEqualTo(String value) {
            addCriterion("ethnic_group =", value, "ethnicGroup");
            return (Criteria) this;
        }

        public Criteria andEthnicGroupNotEqualTo(String value) {
            addCriterion("ethnic_group <>", value, "ethnicGroup");
            return (Criteria) this;
        }

        public Criteria andEthnicGroupGreaterThan(String value) {
            addCriterion("ethnic_group >", value, "ethnicGroup");
            return (Criteria) this;
        }

        public Criteria andEthnicGroupGreaterThanOrEqualTo(String value) {
            addCriterion("ethnic_group >=", value, "ethnicGroup");
            return (Criteria) this;
        }

        public Criteria andEthnicGroupLessThan(String value) {
            addCriterion("ethnic_group <", value, "ethnicGroup");
            return (Criteria) this;
        }

        public Criteria andEthnicGroupLessThanOrEqualTo(String value) {
            addCriterion("ethnic_group <=", value, "ethnicGroup");
            return (Criteria) this;
        }

        public Criteria andEthnicGroupLike(String value) {
            addCriterion("ethnic_group like", value, "ethnicGroup");
            return (Criteria) this;
        }

        public Criteria andEthnicGroupNotLike(String value) {
            addCriterion("ethnic_group not like", value, "ethnicGroup");
            return (Criteria) this;
        }

        public Criteria andEthnicGroupIn(List<String> values) {
            addCriterion("ethnic_group in", values, "ethnicGroup");
            return (Criteria) this;
        }

        public Criteria andEthnicGroupNotIn(List<String> values) {
            addCriterion("ethnic_group not in", values, "ethnicGroup");
            return (Criteria) this;
        }

        public Criteria andEthnicGroupBetween(String value1, String value2) {
            addCriterion("ethnic_group between", value1, value2, "ethnicGroup");
            return (Criteria) this;
        }

        public Criteria andEthnicGroupNotBetween(String value1, String value2) {
            addCriterion("ethnic_group not between", value1, value2, "ethnicGroup");
            return (Criteria) this;
        }

        public Criteria andAdmissionYearIsNull() {
            addCriterion("admission_year is null");
            return (Criteria) this;
        }

        public Criteria andAdmissionYearIsNotNull() {
            addCriterion("admission_year is not null");
            return (Criteria) this;
        }

        public Criteria andAdmissionYearEqualTo(Integer value) {
            addCriterion("admission_year =", value, "admissionYear");
            return (Criteria) this;
        }

        public Criteria andAdmissionYearNotEqualTo(Integer value) {
            addCriterion("admission_year <>", value, "admissionYear");
            return (Criteria) this;
        }

        public Criteria andAdmissionYearGreaterThan(Integer value) {
            addCriterion("admission_year >", value, "admissionYear");
            return (Criteria) this;
        }

        public Criteria andAdmissionYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("admission_year >=", value, "admissionYear");
            return (Criteria) this;
        }

        public Criteria andAdmissionYearLessThan(Integer value) {
            addCriterion("admission_year <", value, "admissionYear");
            return (Criteria) this;
        }

        public Criteria andAdmissionYearLessThanOrEqualTo(Integer value) {
            addCriterion("admission_year <=", value, "admissionYear");
            return (Criteria) this;
        }

        public Criteria andAdmissionYearIn(List<Integer> values) {
            addCriterion("admission_year in", values, "admissionYear");
            return (Criteria) this;
        }

        public Criteria andAdmissionYearNotIn(List<Integer> values) {
            addCriterion("admission_year not in", values, "admissionYear");
            return (Criteria) this;
        }

        public Criteria andAdmissionYearBetween(Integer value1, Integer value2) {
            addCriterion("admission_year between", value1, value2, "admissionYear");
            return (Criteria) this;
        }

        public Criteria andAdmissionYearNotBetween(Integer value1, Integer value2) {
            addCriterion("admission_year not between", value1, value2, "admissionYear");
            return (Criteria) this;
        }

        public Criteria andInstituteIsNull() {
            addCriterion("institute is null");
            return (Criteria) this;
        }

        public Criteria andInstituteIsNotNull() {
            addCriterion("institute is not null");
            return (Criteria) this;
        }

        public Criteria andInstituteEqualTo(String value) {
            addCriterion("institute =", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteNotEqualTo(String value) {
            addCriterion("institute <>", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteGreaterThan(String value) {
            addCriterion("institute >", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteGreaterThanOrEqualTo(String value) {
            addCriterion("institute >=", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteLessThan(String value) {
            addCriterion("institute <", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteLessThanOrEqualTo(String value) {
            addCriterion("institute <=", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteLike(String value) {
            addCriterion("institute like", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteNotLike(String value) {
            addCriterion("institute not like", value, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteIn(List<String> values) {
            addCriterion("institute in", values, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteNotIn(List<String> values) {
            addCriterion("institute not in", values, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteBetween(String value1, String value2) {
            addCriterion("institute between", value1, value2, "institute");
            return (Criteria) this;
        }

        public Criteria andInstituteNotBetween(String value1, String value2) {
            addCriterion("institute not between", value1, value2, "institute");
            return (Criteria) this;
        }

        public Criteria andProfessionIsNull() {
            addCriterion("profession is null");
            return (Criteria) this;
        }

        public Criteria andProfessionIsNotNull() {
            addCriterion("profession is not null");
            return (Criteria) this;
        }

        public Criteria andProfessionEqualTo(String value) {
            addCriterion("profession =", value, "profession");
            return (Criteria) this;
        }

        public Criteria andProfessionNotEqualTo(String value) {
            addCriterion("profession <>", value, "profession");
            return (Criteria) this;
        }

        public Criteria andProfessionGreaterThan(String value) {
            addCriterion("profession >", value, "profession");
            return (Criteria) this;
        }

        public Criteria andProfessionGreaterThanOrEqualTo(String value) {
            addCriterion("profession >=", value, "profession");
            return (Criteria) this;
        }

        public Criteria andProfessionLessThan(String value) {
            addCriterion("profession <", value, "profession");
            return (Criteria) this;
        }

        public Criteria andProfessionLessThanOrEqualTo(String value) {
            addCriterion("profession <=", value, "profession");
            return (Criteria) this;
        }

        public Criteria andProfessionLike(String value) {
            addCriterion("profession like", value, "profession");
            return (Criteria) this;
        }

        public Criteria andProfessionNotLike(String value) {
            addCriterion("profession not like", value, "profession");
            return (Criteria) this;
        }

        public Criteria andProfessionIn(List<String> values) {
            addCriterion("profession in", values, "profession");
            return (Criteria) this;
        }

        public Criteria andProfessionNotIn(List<String> values) {
            addCriterion("profession not in", values, "profession");
            return (Criteria) this;
        }

        public Criteria andProfessionBetween(String value1, String value2) {
            addCriterion("profession between", value1, value2, "profession");
            return (Criteria) this;
        }

        public Criteria andProfessionNotBetween(String value1, String value2) {
            addCriterion("profession not between", value1, value2, "profession");
            return (Criteria) this;
        }

        public Criteria andClassNoIsNull() {
            addCriterion("class_no is null");
            return (Criteria) this;
        }

        public Criteria andClassNoIsNotNull() {
            addCriterion("class_no is not null");
            return (Criteria) this;
        }

        public Criteria andClassNoEqualTo(String value) {
            addCriterion("class_no =", value, "classNo");
            return (Criteria) this;
        }

        public Criteria andClassNoNotEqualTo(String value) {
            addCriterion("class_no <>", value, "classNo");
            return (Criteria) this;
        }

        public Criteria andClassNoGreaterThan(String value) {
            addCriterion("class_no >", value, "classNo");
            return (Criteria) this;
        }

        public Criteria andClassNoGreaterThanOrEqualTo(String value) {
            addCriterion("class_no >=", value, "classNo");
            return (Criteria) this;
        }

        public Criteria andClassNoLessThan(String value) {
            addCriterion("class_no <", value, "classNo");
            return (Criteria) this;
        }

        public Criteria andClassNoLessThanOrEqualTo(String value) {
            addCriterion("class_no <=", value, "classNo");
            return (Criteria) this;
        }

        public Criteria andClassNoLike(String value) {
            addCriterion("class_no like", value, "classNo");
            return (Criteria) this;
        }

        public Criteria andClassNoNotLike(String value) {
            addCriterion("class_no not like", value, "classNo");
            return (Criteria) this;
        }

        public Criteria andClassNoIn(List<String> values) {
            addCriterion("class_no in", values, "classNo");
            return (Criteria) this;
        }

        public Criteria andClassNoNotIn(List<String> values) {
            addCriterion("class_no not in", values, "classNo");
            return (Criteria) this;
        }

        public Criteria andClassNoBetween(String value1, String value2) {
            addCriterion("class_no between", value1, value2, "classNo");
            return (Criteria) this;
        }

        public Criteria andClassNoNotBetween(String value1, String value2) {
            addCriterion("class_no not between", value1, value2, "classNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNull() {
            addCriterion("phone_no is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNotNull() {
            addCriterion("phone_no is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoEqualTo(String value) {
            addCriterion("phone_no =", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotEqualTo(String value) {
            addCriterion("phone_no <>", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThan(String value) {
            addCriterion("phone_no >", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThanOrEqualTo(String value) {
            addCriterion("phone_no >=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThan(String value) {
            addCriterion("phone_no <", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThanOrEqualTo(String value) {
            addCriterion("phone_no <=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLike(String value) {
            addCriterion("phone_no like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotLike(String value) {
            addCriterion("phone_no not like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIn(List<String> values) {
            addCriterion("phone_no in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotIn(List<String> values) {
            addCriterion("phone_no not in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoBetween(String value1, String value2) {
            addCriterion("phone_no between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotBetween(String value1, String value2) {
            addCriterion("phone_no not between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andExamNoIsNull() {
            addCriterion("exam_no is null");
            return (Criteria) this;
        }

        public Criteria andExamNoIsNotNull() {
            addCriterion("exam_no is not null");
            return (Criteria) this;
        }

        public Criteria andExamNoEqualTo(Integer value) {
            addCriterion("exam_no =", value, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoNotEqualTo(Integer value) {
            addCriterion("exam_no <>", value, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoGreaterThan(Integer value) {
            addCriterion("exam_no >", value, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("exam_no >=", value, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoLessThan(Integer value) {
            addCriterion("exam_no <", value, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoLessThanOrEqualTo(Integer value) {
            addCriterion("exam_no <=", value, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoIn(List<Integer> values) {
            addCriterion("exam_no in", values, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoNotIn(List<Integer> values) {
            addCriterion("exam_no not in", values, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoBetween(Integer value1, Integer value2) {
            addCriterion("exam_no between", value1, value2, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamNoNotBetween(Integer value1, Integer value2) {
            addCriterion("exam_no not between", value1, value2, "examNo");
            return (Criteria) this;
        }

        public Criteria andExamTimeIsNull() {
            addCriterion("exam_time is null");
            return (Criteria) this;
        }

        public Criteria andExamTimeIsNotNull() {
            addCriterion("exam_time is not null");
            return (Criteria) this;
        }

        public Criteria andExamTimeEqualTo(Date value) {
            addCriterion("exam_time =", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeNotEqualTo(Date value) {
            addCriterion("exam_time <>", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeGreaterThan(Date value) {
            addCriterion("exam_time >", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("exam_time >=", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeLessThan(Date value) {
            addCriterion("exam_time <", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeLessThanOrEqualTo(Date value) {
            addCriterion("exam_time <=", value, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeIn(List<Date> values) {
            addCriterion("exam_time in", values, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeNotIn(List<Date> values) {
            addCriterion("exam_time not in", values, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeBetween(Date value1, Date value2) {
            addCriterion("exam_time between", value1, value2, "examTime");
            return (Criteria) this;
        }

        public Criteria andExamTimeNotBetween(Date value1, Date value2) {
            addCriterion("exam_time not between", value1, value2, "examTime");
            return (Criteria) this;
        }

        public Criteria andSelectExamTimeIsNull() {
            addCriterion("select_exam_time is null");
            return (Criteria) this;
        }

        public Criteria andSelectExamTimeIsNotNull() {
            addCriterion("select_exam_time is not null");
            return (Criteria) this;
        }

        public Criteria andSelectExamTimeEqualTo(Date value) {
            addCriterion("select_exam_time =", value, "selectExamTime");
            return (Criteria) this;
        }

        public Criteria andSelectExamTimeNotEqualTo(Date value) {
            addCriterion("select_exam_time <>", value, "selectExamTime");
            return (Criteria) this;
        }

        public Criteria andSelectExamTimeGreaterThan(Date value) {
            addCriterion("select_exam_time >", value, "selectExamTime");
            return (Criteria) this;
        }

        public Criteria andSelectExamTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("select_exam_time >=", value, "selectExamTime");
            return (Criteria) this;
        }

        public Criteria andSelectExamTimeLessThan(Date value) {
            addCriterion("select_exam_time <", value, "selectExamTime");
            return (Criteria) this;
        }

        public Criteria andSelectExamTimeLessThanOrEqualTo(Date value) {
            addCriterion("select_exam_time <=", value, "selectExamTime");
            return (Criteria) this;
        }

        public Criteria andSelectExamTimeIn(List<Date> values) {
            addCriterion("select_exam_time in", values, "selectExamTime");
            return (Criteria) this;
        }

        public Criteria andSelectExamTimeNotIn(List<Date> values) {
            addCriterion("select_exam_time not in", values, "selectExamTime");
            return (Criteria) this;
        }

        public Criteria andSelectExamTimeBetween(Date value1, Date value2) {
            addCriterion("select_exam_time between", value1, value2, "selectExamTime");
            return (Criteria) this;
        }

        public Criteria andSelectExamTimeNotBetween(Date value1, Date value2) {
            addCriterion("select_exam_time not between", value1, value2, "selectExamTime");
            return (Criteria) this;
        }

        public Criteria andAppliDeadlineIsNull() {
            addCriterion("appli_deadline is null");
            return (Criteria) this;
        }

        public Criteria andAppliDeadlineIsNotNull() {
            addCriterion("appli_deadline is not null");
            return (Criteria) this;
        }

        public Criteria andAppliDeadlineEqualTo(Date value) {
            addCriterion("appli_deadline =", value, "appliDeadline");
            return (Criteria) this;
        }

        public Criteria andAppliDeadlineNotEqualTo(Date value) {
            addCriterion("appli_deadline <>", value, "appliDeadline");
            return (Criteria) this;
        }

        public Criteria andAppliDeadlineGreaterThan(Date value) {
            addCriterion("appli_deadline >", value, "appliDeadline");
            return (Criteria) this;
        }

        public Criteria andAppliDeadlineGreaterThanOrEqualTo(Date value) {
            addCriterion("appli_deadline >=", value, "appliDeadline");
            return (Criteria) this;
        }

        public Criteria andAppliDeadlineLessThan(Date value) {
            addCriterion("appli_deadline <", value, "appliDeadline");
            return (Criteria) this;
        }

        public Criteria andAppliDeadlineLessThanOrEqualTo(Date value) {
            addCriterion("appli_deadline <=", value, "appliDeadline");
            return (Criteria) this;
        }

        public Criteria andAppliDeadlineIn(List<Date> values) {
            addCriterion("appli_deadline in", values, "appliDeadline");
            return (Criteria) this;
        }

        public Criteria andAppliDeadlineNotIn(List<Date> values) {
            addCriterion("appli_deadline not in", values, "appliDeadline");
            return (Criteria) this;
        }

        public Criteria andAppliDeadlineBetween(Date value1, Date value2) {
            addCriterion("appli_deadline between", value1, value2, "appliDeadline");
            return (Criteria) this;
        }

        public Criteria andAppliDeadlineNotBetween(Date value1, Date value2) {
            addCriterion("appli_deadline not between", value1, value2, "appliDeadline");
            return (Criteria) this;
        }

        public Criteria andCanApplyIsNull() {
            addCriterion("can_apply is null");
            return (Criteria) this;
        }

        public Criteria andCanApplyIsNotNull() {
            addCriterion("can_apply is not null");
            return (Criteria) this;
        }

        public Criteria andCanApplyEqualTo(Byte value) {
            addCriterion("can_apply =", value, "canApply");
            return (Criteria) this;
        }

        public Criteria andCanApplyNotEqualTo(Byte value) {
            addCriterion("can_apply <>", value, "canApply");
            return (Criteria) this;
        }

        public Criteria andCanApplyGreaterThan(Byte value) {
            addCriterion("can_apply >", value, "canApply");
            return (Criteria) this;
        }

        public Criteria andCanApplyGreaterThanOrEqualTo(Byte value) {
            addCriterion("can_apply >=", value, "canApply");
            return (Criteria) this;
        }

        public Criteria andCanApplyLessThan(Byte value) {
            addCriterion("can_apply <", value, "canApply");
            return (Criteria) this;
        }

        public Criteria andCanApplyLessThanOrEqualTo(Byte value) {
            addCriterion("can_apply <=", value, "canApply");
            return (Criteria) this;
        }

        public Criteria andCanApplyIn(List<Byte> values) {
            addCriterion("can_apply in", values, "canApply");
            return (Criteria) this;
        }

        public Criteria andCanApplyNotIn(List<Byte> values) {
            addCriterion("can_apply not in", values, "canApply");
            return (Criteria) this;
        }

        public Criteria andCanApplyBetween(Byte value1, Byte value2) {
            addCriterion("can_apply between", value1, value2, "canApply");
            return (Criteria) this;
        }

        public Criteria andCanApplyNotBetween(Byte value1, Byte value2) {
            addCriterion("can_apply not between", value1, value2, "canApply");
            return (Criteria) this;
        }

        public Criteria andAppliStartsOnIsNull() {
            addCriterion("appli_starts_on is null");
            return (Criteria) this;
        }

        public Criteria andAppliStartsOnIsNotNull() {
            addCriterion("appli_starts_on is not null");
            return (Criteria) this;
        }

        public Criteria andAppliStartsOnEqualTo(Date value) {
            addCriterionForJDBCDate("appli_starts_on =", value, "appliStartsOn");
            return (Criteria) this;
        }

        public Criteria andAppliStartsOnNotEqualTo(Date value) {
            addCriterionForJDBCDate("appli_starts_on <>", value, "appliStartsOn");
            return (Criteria) this;
        }

        public Criteria andAppliStartsOnGreaterThan(Date value) {
            addCriterionForJDBCDate("appli_starts_on >", value, "appliStartsOn");
            return (Criteria) this;
        }

        public Criteria andAppliStartsOnGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("appli_starts_on >=", value, "appliStartsOn");
            return (Criteria) this;
        }

        public Criteria andAppliStartsOnLessThan(Date value) {
            addCriterionForJDBCDate("appli_starts_on <", value, "appliStartsOn");
            return (Criteria) this;
        }

        public Criteria andAppliStartsOnLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("appli_starts_on <=", value, "appliStartsOn");
            return (Criteria) this;
        }

        public Criteria andAppliStartsOnIn(List<Date> values) {
            addCriterionForJDBCDate("appli_starts_on in", values, "appliStartsOn");
            return (Criteria) this;
        }

        public Criteria andAppliStartsOnNotIn(List<Date> values) {
            addCriterionForJDBCDate("appli_starts_on not in", values, "appliStartsOn");
            return (Criteria) this;
        }

        public Criteria andAppliStartsOnBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("appli_starts_on between", value1, value2, "appliStartsOn");
            return (Criteria) this;
        }

        public Criteria andAppliStartsOnNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("appli_starts_on not between", value1, value2, "appliStartsOn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table detailed_application
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 21 21:20:03 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}