package cn.edu.njust.dev.ses.main.model;

import java.util.Date;

public class DetailedGradesEntry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.eid
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.student_id
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.id_no
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private String idNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.uid
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.name
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.gender
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.ethnic_group
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private String ethnicGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.admission_year
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private Integer admissionYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.institute
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private String institute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.profession
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.class_no
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private String classNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.phone_no
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.gid
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.grades
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private Integer grades;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.max_grades
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private Integer maxGrades;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.is_approved
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private Byte isApproved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.grades_problem1
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private Integer gradesProblem1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.grades_problem2
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private Integer gradesProblem2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.grades_problem3
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private Integer gradesProblem3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.grades_problem4
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private Integer gradesProblem4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.grades_problem5
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private Integer gradesProblem5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.exam_no
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private Integer examNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_grades_entry.exam_time
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    private Date examTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.eid
     *
     * @return the value of detailed_grades_entry.eid
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.eid
     *
     * @param eid the value for detailed_grades_entry.eid
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.student_id
     *
     * @return the value of detailed_grades_entry.student_id
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.student_id
     *
     * @param studentId the value for detailed_grades_entry.student_id
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.id_no
     *
     * @return the value of detailed_grades_entry.id_no
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.id_no
     *
     * @param idNo the value for detailed_grades_entry.id_no
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.uid
     *
     * @return the value of detailed_grades_entry.uid
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.uid
     *
     * @param uid the value for detailed_grades_entry.uid
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.name
     *
     * @return the value of detailed_grades_entry.name
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.name
     *
     * @param name the value for detailed_grades_entry.name
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.gender
     *
     * @return the value of detailed_grades_entry.gender
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.gender
     *
     * @param gender the value for detailed_grades_entry.gender
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.ethnic_group
     *
     * @return the value of detailed_grades_entry.ethnic_group
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public String getEthnicGroup() {
        return ethnicGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.ethnic_group
     *
     * @param ethnicGroup the value for detailed_grades_entry.ethnic_group
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setEthnicGroup(String ethnicGroup) {
        this.ethnicGroup = ethnicGroup == null ? null : ethnicGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.admission_year
     *
     * @return the value of detailed_grades_entry.admission_year
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public Integer getAdmissionYear() {
        return admissionYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.admission_year
     *
     * @param admissionYear the value for detailed_grades_entry.admission_year
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setAdmissionYear(Integer admissionYear) {
        this.admissionYear = admissionYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.institute
     *
     * @return the value of detailed_grades_entry.institute
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.institute
     *
     * @param institute the value for detailed_grades_entry.institute
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setInstitute(String institute) {
        this.institute = institute == null ? null : institute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.profession
     *
     * @return the value of detailed_grades_entry.profession
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.profession
     *
     * @param profession the value for detailed_grades_entry.profession
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.class_no
     *
     * @return the value of detailed_grades_entry.class_no
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public String getClassNo() {
        return classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.class_no
     *
     * @param classNo the value for detailed_grades_entry.class_no
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setClassNo(String classNo) {
        this.classNo = classNo == null ? null : classNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.phone_no
     *
     * @return the value of detailed_grades_entry.phone_no
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.phone_no
     *
     * @param phoneNo the value for detailed_grades_entry.phone_no
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.gid
     *
     * @return the value of detailed_grades_entry.gid
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.gid
     *
     * @param gid the value for detailed_grades_entry.gid
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.grades
     *
     * @return the value of detailed_grades_entry.grades
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public Integer getGrades() {
        return grades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.grades
     *
     * @param grades the value for detailed_grades_entry.grades
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setGrades(Integer grades) {
        this.grades = grades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.max_grades
     *
     * @return the value of detailed_grades_entry.max_grades
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public Integer getMaxGrades() {
        return maxGrades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.max_grades
     *
     * @param maxGrades the value for detailed_grades_entry.max_grades
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setMaxGrades(Integer maxGrades) {
        this.maxGrades = maxGrades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.is_approved
     *
     * @return the value of detailed_grades_entry.is_approved
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public Byte getIsApproved() {
        return isApproved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.is_approved
     *
     * @param isApproved the value for detailed_grades_entry.is_approved
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setIsApproved(Byte isApproved) {
        this.isApproved = isApproved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.grades_problem1
     *
     * @return the value of detailed_grades_entry.grades_problem1
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public Integer getGradesProblem1() {
        return gradesProblem1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.grades_problem1
     *
     * @param gradesProblem1 the value for detailed_grades_entry.grades_problem1
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setGradesProblem1(Integer gradesProblem1) {
        this.gradesProblem1 = gradesProblem1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.grades_problem2
     *
     * @return the value of detailed_grades_entry.grades_problem2
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public Integer getGradesProblem2() {
        return gradesProblem2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.grades_problem2
     *
     * @param gradesProblem2 the value for detailed_grades_entry.grades_problem2
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setGradesProblem2(Integer gradesProblem2) {
        this.gradesProblem2 = gradesProblem2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.grades_problem3
     *
     * @return the value of detailed_grades_entry.grades_problem3
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public Integer getGradesProblem3() {
        return gradesProblem3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.grades_problem3
     *
     * @param gradesProblem3 the value for detailed_grades_entry.grades_problem3
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setGradesProblem3(Integer gradesProblem3) {
        this.gradesProblem3 = gradesProblem3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.grades_problem4
     *
     * @return the value of detailed_grades_entry.grades_problem4
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public Integer getGradesProblem4() {
        return gradesProblem4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.grades_problem4
     *
     * @param gradesProblem4 the value for detailed_grades_entry.grades_problem4
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setGradesProblem4(Integer gradesProblem4) {
        this.gradesProblem4 = gradesProblem4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.grades_problem5
     *
     * @return the value of detailed_grades_entry.grades_problem5
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public Integer getGradesProblem5() {
        return gradesProblem5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.grades_problem5
     *
     * @param gradesProblem5 the value for detailed_grades_entry.grades_problem5
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setGradesProblem5(Integer gradesProblem5) {
        this.gradesProblem5 = gradesProblem5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.exam_no
     *
     * @return the value of detailed_grades_entry.exam_no
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public Integer getExamNo() {
        return examNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.exam_no
     *
     * @param examNo the value for detailed_grades_entry.exam_no
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setExamNo(Integer examNo) {
        this.examNo = examNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_grades_entry.exam_time
     *
     * @return the value of detailed_grades_entry.exam_time
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public Date getExamTime() {
        return examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_grades_entry.exam_time
     *
     * @param examTime the value for detailed_grades_entry.exam_time
     *
     * @mbg.generated Thu Dec 19 17:19:05 CST 2019
     */
    public void setExamTime(Date examTime) {
        this.examTime = examTime;
    }
}