package cn.edu.njust.dev.ses.main.model;

import java.util.Date;

public class DetailedApplication {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.eid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.uid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.aid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.app_time
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Date appTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.app_status
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private String appStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.name
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.student_id
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.gender
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.id_no
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private String idNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.ethnic_group
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private String ethnicGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.admission_year
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Integer admissionYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.institute
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private String institute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.profession
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.class_no
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private String classNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.phone_no
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.exam_no
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Integer examNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.exam_time
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Date examTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.select_exam_time
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Date selectExamTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.appli_deadline
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Date appliDeadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.can_apply
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Byte canApply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_application.appli_starts_on
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    private Date appliStartsOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public DetailedApplication(Integer eid, Integer uid, Integer aid, Date appTime, String appStatus, String name, String studentId, String gender, String idNo, String ethnicGroup, Integer admissionYear, String institute, String profession, String classNo, String phoneNo, Integer examNo, Date examTime, Date selectExamTime, Date appliDeadline, Byte canApply, Date appliStartsOn) {
        this.eid = eid;
        this.uid = uid;
        this.aid = aid;
        this.appTime = appTime;
        this.appStatus = appStatus;
        this.name = name;
        this.studentId = studentId;
        this.gender = gender;
        this.idNo = idNo;
        this.ethnicGroup = ethnicGroup;
        this.admissionYear = admissionYear;
        this.institute = institute;
        this.profession = profession;
        this.classNo = classNo;
        this.phoneNo = phoneNo;
        this.examNo = examNo;
        this.examTime = examTime;
        this.selectExamTime = selectExamTime;
        this.appliDeadline = appliDeadline;
        this.canApply = canApply;
        this.appliStartsOn = appliStartsOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public DetailedApplication() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.eid
     *
     * @return the value of detailed_application.eid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.eid
     *
     * @param eid the value for detailed_application.eid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.uid
     *
     * @return the value of detailed_application.uid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.uid
     *
     * @param uid the value for detailed_application.uid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.aid
     *
     * @return the value of detailed_application.aid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.aid
     *
     * @param aid the value for detailed_application.aid
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.app_time
     *
     * @return the value of detailed_application.app_time
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Date getAppTime() {
        return appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.app_time
     *
     * @param appTime the value for detailed_application.app_time
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setAppTime(Date appTime) {
        this.appTime = appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.app_status
     *
     * @return the value of detailed_application.app_status
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.app_status
     *
     * @param appStatus the value for detailed_application.app_status
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setAppStatus(String appStatus) {
        this.appStatus = appStatus == null ? null : appStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.name
     *
     * @return the value of detailed_application.name
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.name
     *
     * @param name the value for detailed_application.name
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.student_id
     *
     * @return the value of detailed_application.student_id
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.student_id
     *
     * @param studentId the value for detailed_application.student_id
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.gender
     *
     * @return the value of detailed_application.gender
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.gender
     *
     * @param gender the value for detailed_application.gender
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.id_no
     *
     * @return the value of detailed_application.id_no
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.id_no
     *
     * @param idNo the value for detailed_application.id_no
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.ethnic_group
     *
     * @return the value of detailed_application.ethnic_group
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public String getEthnicGroup() {
        return ethnicGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.ethnic_group
     *
     * @param ethnicGroup the value for detailed_application.ethnic_group
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setEthnicGroup(String ethnicGroup) {
        this.ethnicGroup = ethnicGroup == null ? null : ethnicGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.admission_year
     *
     * @return the value of detailed_application.admission_year
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Integer getAdmissionYear() {
        return admissionYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.admission_year
     *
     * @param admissionYear the value for detailed_application.admission_year
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setAdmissionYear(Integer admissionYear) {
        this.admissionYear = admissionYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.institute
     *
     * @return the value of detailed_application.institute
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.institute
     *
     * @param institute the value for detailed_application.institute
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setInstitute(String institute) {
        this.institute = institute == null ? null : institute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.profession
     *
     * @return the value of detailed_application.profession
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.profession
     *
     * @param profession the value for detailed_application.profession
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.class_no
     *
     * @return the value of detailed_application.class_no
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public String getClassNo() {
        return classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.class_no
     *
     * @param classNo the value for detailed_application.class_no
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setClassNo(String classNo) {
        this.classNo = classNo == null ? null : classNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.phone_no
     *
     * @return the value of detailed_application.phone_no
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.phone_no
     *
     * @param phoneNo the value for detailed_application.phone_no
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.exam_no
     *
     * @return the value of detailed_application.exam_no
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Integer getExamNo() {
        return examNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.exam_no
     *
     * @param examNo the value for detailed_application.exam_no
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setExamNo(Integer examNo) {
        this.examNo = examNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.exam_time
     *
     * @return the value of detailed_application.exam_time
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Date getExamTime() {
        return examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.exam_time
     *
     * @param examTime the value for detailed_application.exam_time
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setExamTime(Date examTime) {
        this.examTime = examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.select_exam_time
     *
     * @return the value of detailed_application.select_exam_time
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Date getSelectExamTime() {
        return selectExamTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.select_exam_time
     *
     * @param selectExamTime the value for detailed_application.select_exam_time
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setSelectExamTime(Date selectExamTime) {
        this.selectExamTime = selectExamTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.appli_deadline
     *
     * @return the value of detailed_application.appli_deadline
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Date getAppliDeadline() {
        return appliDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.appli_deadline
     *
     * @param appliDeadline the value for detailed_application.appli_deadline
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setAppliDeadline(Date appliDeadline) {
        this.appliDeadline = appliDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.can_apply
     *
     * @return the value of detailed_application.can_apply
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Byte getCanApply() {
        return canApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.can_apply
     *
     * @param canApply the value for detailed_application.can_apply
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setCanApply(Byte canApply) {
        this.canApply = canApply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_application.appli_starts_on
     *
     * @return the value of detailed_application.appli_starts_on
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public Date getAppliStartsOn() {
        return appliStartsOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_application.appli_starts_on
     *
     * @param appliStartsOn the value for detailed_application.appli_starts_on
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    public void setAppliStartsOn(Date appliStartsOn) {
        this.appliStartsOn = appliStartsOn;
    }
}