package cn.edu.njust.dev.ses.main.model;

import java.util.Date;

public class DetailedSelectRankEntry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.eid
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.student_id
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.id_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private String idNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.uid
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.name
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.gender
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.ethnic_group
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private String ethnicGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.admission_year
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private Integer admissionYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.institute
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private String institute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.profession
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.class_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private String classNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.phone_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.reid
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private Integer reid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.rank_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private Integer rankNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.exam_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private Integer examNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detailed_select_rank.exam_time
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    private Date examTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.eid
     *
     * @return the value of detailed_select_rank.eid
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.eid
     *
     * @param eid the value for detailed_select_rank.eid
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.student_id
     *
     * @return the value of detailed_select_rank.student_id
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.student_id
     *
     * @param studentId the value for detailed_select_rank.student_id
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.id_no
     *
     * @return the value of detailed_select_rank.id_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.id_no
     *
     * @param idNo the value for detailed_select_rank.id_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.uid
     *
     * @return the value of detailed_select_rank.uid
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.uid
     *
     * @param uid the value for detailed_select_rank.uid
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.name
     *
     * @return the value of detailed_select_rank.name
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.name
     *
     * @param name the value for detailed_select_rank.name
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.gender
     *
     * @return the value of detailed_select_rank.gender
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.gender
     *
     * @param gender the value for detailed_select_rank.gender
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.ethnic_group
     *
     * @return the value of detailed_select_rank.ethnic_group
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public String getEthnicGroup() {
        return ethnicGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.ethnic_group
     *
     * @param ethnicGroup the value for detailed_select_rank.ethnic_group
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setEthnicGroup(String ethnicGroup) {
        this.ethnicGroup = ethnicGroup == null ? null : ethnicGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.admission_year
     *
     * @return the value of detailed_select_rank.admission_year
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public Integer getAdmissionYear() {
        return admissionYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.admission_year
     *
     * @param admissionYear the value for detailed_select_rank.admission_year
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setAdmissionYear(Integer admissionYear) {
        this.admissionYear = admissionYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.institute
     *
     * @return the value of detailed_select_rank.institute
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.institute
     *
     * @param institute the value for detailed_select_rank.institute
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setInstitute(String institute) {
        this.institute = institute == null ? null : institute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.profession
     *
     * @return the value of detailed_select_rank.profession
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.profession
     *
     * @param profession the value for detailed_select_rank.profession
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.class_no
     *
     * @return the value of detailed_select_rank.class_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public String getClassNo() {
        return classNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.class_no
     *
     * @param classNo the value for detailed_select_rank.class_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setClassNo(String classNo) {
        this.classNo = classNo == null ? null : classNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.phone_no
     *
     * @return the value of detailed_select_rank.phone_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.phone_no
     *
     * @param phoneNo the value for detailed_select_rank.phone_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.reid
     *
     * @return the value of detailed_select_rank.reid
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public Integer getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.reid
     *
     * @param reid the value for detailed_select_rank.reid
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setReid(Integer reid) {
        this.reid = reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.rank_no
     *
     * @return the value of detailed_select_rank.rank_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public Integer getRankNo() {
        return rankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.rank_no
     *
     * @param rankNo the value for detailed_select_rank.rank_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setRankNo(Integer rankNo) {
        this.rankNo = rankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.exam_no
     *
     * @return the value of detailed_select_rank.exam_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public Integer getExamNo() {
        return examNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.exam_no
     *
     * @param examNo the value for detailed_select_rank.exam_no
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setExamNo(Integer examNo) {
        this.examNo = examNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detailed_select_rank.exam_time
     *
     * @return the value of detailed_select_rank.exam_time
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public Date getExamTime() {
        return examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detailed_select_rank.exam_time
     *
     * @param examTime the value for detailed_select_rank.exam_time
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    public void setExamTime(Date examTime) {
        this.examTime = examTime;
    }
}