package cn.edu.njust.dev.ses.main.model;

public class GradesEntry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades_entry.gid
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades_entry.grades
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    private Integer grades;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades_entry.eid
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades_entry.student_id
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades_entry.id_no
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    private String idNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades_entry.max_grades
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    private Integer maxGrades;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades_entry.is_approved
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    private Boolean isApproved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades_entry.grades_problem1
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    private Integer gradesProblem1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades_entry.grades_problem2
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    private Integer gradesProblem2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades_entry.grades_problem3
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    private Integer gradesProblem3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades_entry.grades_problem4
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    private Integer gradesProblem4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grades_entry.grades_problem5
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    private Integer gradesProblem5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades_entry.gid
     *
     * @return the value of grades_entry.gid
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades_entry.gid
     *
     * @param gid the value for grades_entry.gid
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades_entry.grades
     *
     * @return the value of grades_entry.grades
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public Integer getGrades() {
        return grades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades_entry.grades
     *
     * @param grades the value for grades_entry.grades
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public void setGrades(Integer grades) {
        this.grades = grades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades_entry.eid
     *
     * @return the value of grades_entry.eid
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades_entry.eid
     *
     * @param eid the value for grades_entry.eid
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades_entry.student_id
     *
     * @return the value of grades_entry.student_id
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades_entry.student_id
     *
     * @param studentId the value for grades_entry.student_id
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades_entry.id_no
     *
     * @return the value of grades_entry.id_no
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades_entry.id_no
     *
     * @param idNo the value for grades_entry.id_no
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades_entry.max_grades
     *
     * @return the value of grades_entry.max_grades
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public Integer getMaxGrades() {
        return maxGrades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades_entry.max_grades
     *
     * @param maxGrades the value for grades_entry.max_grades
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public void setMaxGrades(Integer maxGrades) {
        this.maxGrades = maxGrades;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades_entry.is_approved
     *
     * @return the value of grades_entry.is_approved
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public Boolean getIsApproved() {
        return isApproved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades_entry.is_approved
     *
     * @param isApproved the value for grades_entry.is_approved
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public void setIsApproved(Boolean isApproved) {
        this.isApproved = isApproved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades_entry.grades_problem1
     *
     * @return the value of grades_entry.grades_problem1
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public Integer getGradesProblem1() {
        return gradesProblem1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades_entry.grades_problem1
     *
     * @param gradesProblem1 the value for grades_entry.grades_problem1
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public void setGradesProblem1(Integer gradesProblem1) {
        this.gradesProblem1 = gradesProblem1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades_entry.grades_problem2
     *
     * @return the value of grades_entry.grades_problem2
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public Integer getGradesProblem2() {
        return gradesProblem2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades_entry.grades_problem2
     *
     * @param gradesProblem2 the value for grades_entry.grades_problem2
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public void setGradesProblem2(Integer gradesProblem2) {
        this.gradesProblem2 = gradesProblem2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades_entry.grades_problem3
     *
     * @return the value of grades_entry.grades_problem3
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public Integer getGradesProblem3() {
        return gradesProblem3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades_entry.grades_problem3
     *
     * @param gradesProblem3 the value for grades_entry.grades_problem3
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public void setGradesProblem3(Integer gradesProblem3) {
        this.gradesProblem3 = gradesProblem3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades_entry.grades_problem4
     *
     * @return the value of grades_entry.grades_problem4
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public Integer getGradesProblem4() {
        return gradesProblem4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades_entry.grades_problem4
     *
     * @param gradesProblem4 the value for grades_entry.grades_problem4
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public void setGradesProblem4(Integer gradesProblem4) {
        this.gradesProblem4 = gradesProblem4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grades_entry.grades_problem5
     *
     * @return the value of grades_entry.grades_problem5
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public Integer getGradesProblem5() {
        return gradesProblem5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grades_entry.grades_problem5
     *
     * @param gradesProblem5 the value for grades_entry.grades_problem5
     *
     * @mbg.generated Wed Dec 18 16:26:00 CST 2019
     */
    public void setGradesProblem5(Integer gradesProblem5) {
        this.gradesProblem5 = gradesProblem5;
    }
}