package cn.edu.njust.dev.ses.main.model;

import java.util.ArrayList;
import java.util.List;

public class GradesEntryProofExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    public GradesEntryProofExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGidIsNull() {
            addCriterion("gid is null");
            return (Criteria) this;
        }

        public Criteria andGidIsNotNull() {
            addCriterion("gid is not null");
            return (Criteria) this;
        }

        public Criteria andGidEqualTo(Integer value) {
            addCriterion("gid =", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotEqualTo(Integer value) {
            addCriterion("gid <>", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThan(Integer value) {
            addCriterion("gid >", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThanOrEqualTo(Integer value) {
            addCriterion("gid >=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThan(Integer value) {
            addCriterion("gid <", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThanOrEqualTo(Integer value) {
            addCriterion("gid <=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidIn(List<Integer> values) {
            addCriterion("gid in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotIn(List<Integer> values) {
            addCriterion("gid not in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidBetween(Integer value1, Integer value2) {
            addCriterion("gid between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotBetween(Integer value1, Integer value2) {
            addCriterion("gid not between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andProofUrlIsNull() {
            addCriterion("proof_url is null");
            return (Criteria) this;
        }

        public Criteria andProofUrlIsNotNull() {
            addCriterion("proof_url is not null");
            return (Criteria) this;
        }

        public Criteria andProofUrlEqualTo(String value) {
            addCriterion("proof_url =", value, "proofUrl");
            return (Criteria) this;
        }

        public Criteria andProofUrlNotEqualTo(String value) {
            addCriterion("proof_url <>", value, "proofUrl");
            return (Criteria) this;
        }

        public Criteria andProofUrlGreaterThan(String value) {
            addCriterion("proof_url >", value, "proofUrl");
            return (Criteria) this;
        }

        public Criteria andProofUrlGreaterThanOrEqualTo(String value) {
            addCriterion("proof_url >=", value, "proofUrl");
            return (Criteria) this;
        }

        public Criteria andProofUrlLessThan(String value) {
            addCriterion("proof_url <", value, "proofUrl");
            return (Criteria) this;
        }

        public Criteria andProofUrlLessThanOrEqualTo(String value) {
            addCriterion("proof_url <=", value, "proofUrl");
            return (Criteria) this;
        }

        public Criteria andProofUrlLike(String value) {
            addCriterion("proof_url like", value, "proofUrl");
            return (Criteria) this;
        }

        public Criteria andProofUrlNotLike(String value) {
            addCriterion("proof_url not like", value, "proofUrl");
            return (Criteria) this;
        }

        public Criteria andProofUrlIn(List<String> values) {
            addCriterion("proof_url in", values, "proofUrl");
            return (Criteria) this;
        }

        public Criteria andProofUrlNotIn(List<String> values) {
            addCriterion("proof_url not in", values, "proofUrl");
            return (Criteria) this;
        }

        public Criteria andProofUrlBetween(String value1, String value2) {
            addCriterion("proof_url between", value1, value2, "proofUrl");
            return (Criteria) this;
        }

        public Criteria andProofUrlNotBetween(String value1, String value2) {
            addCriterion("proof_url not between", value1, value2, "proofUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table grades_entry_proof
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 18 11:45:27 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table grades_entry_proof
     *
     * @mbg.generated Wed Dec 18 11:45:27 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}