package cn.edu.njust.dev.ses.main.model;

public class SelectRankEntry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_rank_entry.reid
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    private Integer reid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_rank_entry.uid
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_rank_entry.rank_no
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    private Integer rankNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_rank_entry.eid
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_rank_entry.id_no
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    private String idNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_rank_entry
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    public SelectRankEntry(Integer reid, Integer uid, Integer rankNo, Integer eid, String idNo) {
        this.reid = reid;
        this.uid = uid;
        this.rankNo = rankNo;
        this.eid = eid;
        this.idNo = idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_rank_entry
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    public SelectRankEntry() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_rank_entry.reid
     *
     * @return the value of select_rank_entry.reid
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    public Integer getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_rank_entry.reid
     *
     * @param reid the value for select_rank_entry.reid
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    public void setReid(Integer reid) {
        this.reid = reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_rank_entry.uid
     *
     * @return the value of select_rank_entry.uid
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_rank_entry.uid
     *
     * @param uid the value for select_rank_entry.uid
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_rank_entry.rank_no
     *
     * @return the value of select_rank_entry.rank_no
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    public Integer getRankNo() {
        return rankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_rank_entry.rank_no
     *
     * @param rankNo the value for select_rank_entry.rank_no
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    public void setRankNo(Integer rankNo) {
        this.rankNo = rankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_rank_entry.eid
     *
     * @return the value of select_rank_entry.eid
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_rank_entry.eid
     *
     * @param eid the value for select_rank_entry.eid
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_rank_entry.id_no
     *
     * @return the value of select_rank_entry.id_no
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_rank_entry.id_no
     *
     * @param idNo the value for select_rank_entry.id_no
     *
     * @mbg.generated Sat Dec 21 13:34:00 CST 2019
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }
}