package cn.edu.njust.dev.ses.main.model;

public class SelectRankEntry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_rank_entry.reid
     *
     * @mbg.generated Wed Dec 18 08:59:36 CST 2019
     */
    private Integer reid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_rank_entry.uid
     *
     * @mbg.generated Wed Dec 18 08:59:36 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_rank_entry.rank
     *
     * @mbg.generated Wed Dec 18 08:59:36 CST 2019
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_rank_entry.eid
     *
     * @mbg.generated Wed Dec 18 08:59:36 CST 2019
     */
    private Integer eid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_rank_entry.reid
     *
     * @return the value of select_rank_entry.reid
     *
     * @mbg.generated Wed Dec 18 08:59:36 CST 2019
     */
    public Integer getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_rank_entry.reid
     *
     * @param reid the value for select_rank_entry.reid
     *
     * @mbg.generated Wed Dec 18 08:59:36 CST 2019
     */
    public void setReid(Integer reid) {
        this.reid = reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_rank_entry.uid
     *
     * @return the value of select_rank_entry.uid
     *
     * @mbg.generated Wed Dec 18 08:59:36 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_rank_entry.uid
     *
     * @param uid the value for select_rank_entry.uid
     *
     * @mbg.generated Wed Dec 18 08:59:36 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_rank_entry.rank
     *
     * @return the value of select_rank_entry.rank
     *
     * @mbg.generated Wed Dec 18 08:59:36 CST 2019
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_rank_entry.rank
     *
     * @param rank the value for select_rank_entry.rank
     *
     * @mbg.generated Wed Dec 18 08:59:36 CST 2019
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_rank_entry.eid
     *
     * @return the value of select_rank_entry.eid
     *
     * @mbg.generated Wed Dec 18 08:59:36 CST 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_rank_entry.eid
     *
     * @param eid the value for select_rank_entry.eid
     *
     * @mbg.generated Wed Dec 18 08:59:36 CST 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }
}