package cn.edu.njust.dev.ses.main.mapper;

import cn.edu.njust.dev.ses.main.model.DetailedSelectRankEntry;
import cn.edu.njust.dev.ses.main.model.DetailedSelectRankEntryExample;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface DetailedSelectRankEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_select_rank
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    long countByExample(DetailedSelectRankEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_select_rank
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    List<DetailedSelectRankEntry> selectByExampleWithRowbounds(DetailedSelectRankEntryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_select_rank
     *
     * @mbg.generated Fri Dec 20 21:52:51 CST 2019
     */
    List<DetailedSelectRankEntry> selectByExample(DetailedSelectRankEntryExample example);
}