package cn.edu.njust.dev.ses.main.mapper;

import cn.edu.njust.dev.ses.main.model.DetailedApplication;
import cn.edu.njust.dev.ses.main.model.DetailedApplicationExample;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface DetailedApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    long countByExample(DetailedApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    List<DetailedApplication> selectByExampleWithRowbounds(DetailedApplicationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detailed_application
     *
     * @mbg.generated Sat Dec 21 21:20:03 CST 2019
     */
    List<DetailedApplication> selectByExample(DetailedApplicationExample example);
}