package cn.edu.njust.dev.ses.main.mapper;

import cn.edu.njust.dev.ses.main.model.UserToken;
import cn.edu.njust.dev.ses.main.model.UserTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Wed Dec 11 16:44:56 CST 2019
     */
    long countByExample(UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Wed Dec 11 16:44:56 CST 2019
     */
    int deleteByExample(UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Wed Dec 11 16:44:56 CST 2019
     */
    int deleteByPrimaryKey(Integer sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Wed Dec 11 16:44:56 CST 2019
     */
    int insert(UserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Wed Dec 11 16:44:56 CST 2019
     */
    int insertSelective(UserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Wed Dec 11 16:44:56 CST 2019
     */
    List<UserToken> selectByExampleWithRowbounds(UserTokenExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Wed Dec 11 16:44:56 CST 2019
     */
    List<UserToken> selectByExample(UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Wed Dec 11 16:44:56 CST 2019
     */
    UserToken selectByPrimaryKey(Integer sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Wed Dec 11 16:44:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserToken record, @Param("example") UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Wed Dec 11 16:44:56 CST 2019
     */
    int updateByExample(@Param("record") UserToken record, @Param("example") UserTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Wed Dec 11 16:44:56 CST 2019
     */
    int updateByPrimaryKeySelective(UserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_token
     *
     * @mbg.generated Wed Dec 11 16:44:56 CST 2019
     */
    int updateByPrimaryKey(UserToken record);
}